name: complexWorkflow

on: push

jobs:
  j1:
    name: jobOne
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: echo `date`

  j2:
    name: jobTwo
    runs-on: windows-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: Get-Date

  j3:
    name: jobThree
    runs-on: macos-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: echo `date`

  j4:
    needs: [j1, j2, j3]
    name: jobFour
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: echo `date`
  
